# Configurazione SAC
policy: "MultiInputPolicy"
learning_rate: "constant_0.0003"
n_timesteps: 2000000 # numero totale di timesteps per l'addestramento
batch_size: 512         
buffer_size: 10_000         
learning_starts: 10000  # quando iniziare apprendere la policy       
train_freq: 1               
gradient_steps: 1           
action_noise: null          
ent_coef: "auto"           
target_update_interval: 1   
target_entropy: "auto"      
gamma: 0.99                
tau: 0.005                 
seed: 42                   
device: "auto"       