# Configurazione SAC
policy: "MultiInputPolicy"
n_timesteps: 20_000
learning_rate: "constant_0.0003"
batch_size: 256              
buffer_size: 10_000         
learning_starts: 1         
train_freq: 1               
gradient_steps: 1           
action_noise: null          
ent_coef: "auto"           
target_update_interval: 1   
target_entropy: "auto"      
gamma: 0.99                
tau: 0.005                 
seed: 42                   
device: "auto"       
tensorboard_log: "./sac_tensorboard/"      